### ISSUE TITLE
ImportError: No module named pygcode

### ISSUE THREAD

**Issue by harrycomeon** [mywisdomfly/drawing_manipulator#1]
运行：
roslaunch draw_core start_draw.launch

ImportError: No module named pygcode

![image](https://user-images.githubusercontent.com/28645542/104087515-33f47780-529b-11eb-99f8-e8390fb6486c.png)

安装
pip install pygcode

**Comment by li-haojia** [comment]
Thanks a lot!

**Comment by harrycomeon** [comment]
You are welcome！

Haojia Li <notifications@github.com> 于2021年1月10日周日 下午10:47写道：
